name: jwt_decode
description: A Dart package to decode jsonwebtokens, and to chack and give its expiry dates
version: 0.1.0
homepage: https://github.com/sidsbrmnn/jwt_decode

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
