name: jwt_decode
description: A Dart package to decode jsonwebtokens
version: 0.0.1
homepage: https://github.com/sidsbrmnn/jwt_decode

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
